### ISSUE TITLE
Utils

### ISSUE THREAD

**Issue by PastaLaPate** [Margouta/PluginOpenMC#1]
Avant de commencer à faire les fonctionnalitées faisont un gros utils pour éviter de se répéter avec des classes pour les crafts items entitées etc du style un OpenMCEntity OpenMCPlayer OpenMCMob OpenMCRecipe etc

**Comment by Marvideo2009** [comment]
Bonne idee

**Comment by HiNett** [comment]
@Margouta possible de fermer l'issue ?
Issue inutile :)
