### ISSUE TITLE
[BUG] Pleins de bug avec les TEAMS

### ISSUE THREAD

**Issue by AxenoDev** [Margouta/PluginOpenMC#177]
Le système de teams à pleins de bug...
Quant on veux /team leave cela nous dit que nous sommes dans aucune team alors que si.
Quant on veux leave dans le menu cela nous dit qu'on leave la team alors que non
Quant on veux delete la team alors que l'on est 2 ou plus cela ne marche pas

**Comment by AxenoDev** [comment]
On peux aussi créer plusieurs team avec le même nom

**Comment by Xernas78** [comment]
J’avais Fix tous ces bugs mais vu que @koneiii à refait les méthodes en un peu plus propre et en utilisant sa Lib ça a du casser quelques trucs

**Comment by koneiii** [comment]
MDRR JAI RIEN RETOUCHERR MDRMRMRMR j'ai juste adapté a la commande api

**Comment by MathiasDPX** [comment]
#197

**Comment by Vincentcestmoi** [comment]
Le /teammsg ne marche pas (il affiche que je n'appartient à aucune team)

**Comment by AxillityWasGay** [comment]
> @Vincentcestmoi: Le /teammsg ne marche pas (il affiche que je n'appartient à aucune team)

C'est une command vanilla, pas dans le plugin, normal que ça marche pas.
