### ISSUE TITLE
[BUG] Deco reco rends impossible l'ouverture de sa tombe

### ISSUE THREAD

**Issue by ddemile** [Margouta/PluginOpenMC#179]
Quand un meurt, on a une tombe qu'on peux ouvrir en cliquant dessus mais dès qu'on se deco et reco, même si on n'as pas récupérer le contenu de sa tombe, il devient impossible de l'ouvrir

**Comment by Martinou2x** [comment]
je règle ça

**Comment by MathiasDPX** [comment]
> je règle ça

mets un lien vers ton commit

**Comment by Martinou2x** [comment]
en fait normalement ça fonctionnait déjà mais : https://github.com/Margouta/PluginOpenMC/pull/182/commits/368813a81134f55278fc33f32fce64890e2abab9
