### ISSUE TITLE
[BUG] Son dans chat même si pseudo non envoyé par un joueur.

### ISSUE THREAD

**Issue by Margouta** [Margouta/PluginOpenMC#181]
En gros à chaque message on a le son de notif de mention car le pseudo est dans le message (après le préfixe).

**Comment by MathiasDPX** [comment]
Tu peux donner un peu de contexte ?
Si c'est un serveur privé ou le serveur de dev ?
Car ce n'est pas sensé arrivé
![Screenshot_20240713-124005](https://github.com/user-attachments/assets/9511f82d-c7d8-4e4c-b42d-f779ed8da35a)

**Comment by MathiasDPX** [comment]
Fix
