### ISSUE TITLE
[BUG] /link

### ISSUE THREAD

**Issue by MagnetoCraft** [Margouta/PluginOpenMC#183]
Lorsque j'effectue la commande /link pour la première fois, je reçois le message d'erreur : "Vous avez déjà un code de vérifications" alors que je n'en ais pas
![Screenshot_20240713_152435](https://github.com/user-attachments/assets/9e696d96-06a7-4366-9902-938700ec52c9)

**Comment by AxenoDev** [comment]
Je pourrais avoir plus d'indication ? genre c'est votre serveur local ?

**Comment by Margouta** [comment]
Je pense que le problème vient du fait que le bot est sur la base de donnée de Production et non sur celle du dev :)

**Comment by AxenoDev** [comment]
nan c'est pas ça
Içi ça check si dans la dbb MySQL set dans ton config.yml si il n'y a pas déjà un code qui existe

**Comment by Margouta** [comment]
dans la db de production, la table est vide

**Comment by AxenoDev** [comment]
Bug réglé
