### ISSUE TITLE
Bug avec le /feature player <player>

### ISSUE THREAD

**Issue by AxenoDev** [Margouta/PluginOpenMC#213]
Au lieu de get les features du player que l'on met en args ça prend les features du player qui execute la commande
![image](https://github.com/user-attachments/assets/386375fd-c01c-4ba6-8578-27e3ae88ddf5)

**Comment by MathiasDPX** [comment]
je fini ma game et je fix ça

**Comment by MathiasDPX** [comment]
Parceque ils sont aux nom d'Axeno
