### ISSUE TITLE
bug dupli

### ISSUE THREAD

**Issue by Margouta** [Margouta/PluginOpenMC#235]
@Xernas78 
![image](https://github.com/user-attachments/assets/e5389c81-d35d-4eab-a81b-c6ecd5856895)

**Comment by Xernas78** [comment]
Pas moi j’ai pas fait team money, c’est un ajout de qq d’autre

**Comment by Xernas78** [comment]
Jamais de la vie je laisse un bug aussi obvious

**Comment by Armibule** [comment]
C'est un problème de permis peut être il fait voir

**Comment by Margouta** [comment]
nope, c'est un bug

**Comment by MathiasDPX** [comment]
L'utilisation de ce bug vous offrira un ban perm
voila bonne nuit
