### ISSUE TITLE
[BUG] Passage à travers les blocs avec le /taille

### ISSUE THREAD

**Issue by Artcas2** [Margouta/PluginOpenMC#248]
On peut traverser à travers les blocs :
Etape 1: /taille 100
Etape 2: Se coller contre un bloc
Etape 3: /taille 200
Etape 4: Foncer de bloc en sprintant

Ptite vidéo : https://github.com/user-attachments/assets/2090e56e-a2c3-4d70-8527-8bf072292a8c

Le meme bug m'est déjà arrivé sur mon serveur, je l'ai fix comme ceci :
Quand le joueur fait la commande on enregistre sa position: `Location beforeLocation = player.getLocation();`
Puis après avoir fait réduire la taille du joueur on check avec un runnable si le joueur est dans un block (en retirant les tapis, blocs sans collisions, etc. à compléter) si oui on le fait rollback (ici au centre du bloc au cas où, en conservant sa direction)
```java
new BukkitRunnable() {
    private int timer = 1;
    
    @Override
    public void run() {
        if (timer > 20) {
            cancel();
            return;
        }
    
        Location location = player.getLocation();
        
        if (!location.getBlock().isPassable() && !location.getBlock().getType().name().contains("CARPET") && !location.getBlock().isEmpty()) {
            player.teleport(beforeLocation.getBlock().getLocation().add(0.5, 0, 0.5).setDirection(player.getLocation().getDirection()));
        }
        
        timer++;
  }
}.runTaskTimer(plugin, 0, 1);
```

**Comment by Artcas2** [comment]
Y'avais déjà une issue ouverte à ce sujet mais je me suis dit que j'allais en ouvrir une autre avec plus de détails...

**Comment by MathiasDPX** [comment]
#176 Duplicate
