### ISSUE TITLE
bug tp 

### ISSUE THREAD

**Issue by Ricorsse** [Margouta/PluginOpenMC#287]
bug pour ce tp a un autre joueur  message  " you do not have permission tu use this command

**Comment by AxenoDev** [comment]
Normale, c'est pas un bug tu n'a juste pas la permissions de faire /tp, mais essaye /tpa

**Comment by Ricorsse** [comment]
autant pour moi c'est le /tps qui ne fonctionne pas

**Comment by Armibule** [comment]
Ducoup on peut fermer l'issue ?

**Comment by Ricorsse** [comment]
pour ma par ca ne marche toujour pas soi ca me met qu il y as deja une demande de tp en attente soi   que j ai pas la permission
