### ISSUE TITLE
Problème commande

### ISSUE THREAD

**Issue by AxillityWasGay** [Margouta/PluginOpenMC#290]
J'ai un problème, j'ai codé une fonctionnalité, si tu écris /tpa sans écrire un nom, ça devrait mettre un GUI, mais y'a un message qui pop "You need to specify a value for the joueur!", qui n'est pas dans mon code. La commande /tpa est dans:

core -> tpa

TPACommand.java
TPAQueue.java
Tpacceptcommand.java
Tpdenycommand.java
Tpcancelcommand.java

(Je n'ai pas encore trouvé où est ce message.)

**Comment by fuzeblocks** [comment]
Peut être parce que tu utilises l'annotation Named
![image](https://github.com/user-attachments/assets/506a2e33-39c9-46fc-b5de-f02b97a7306f)

**Comment by AxenoDev** [comment]
Tu n'a pas test ton plugin 😡 😡 😡

**Comment by fuzeblocks** [comment]
> Tu n'a pas test ton plugin 😡 😡 😡

Bah si il a une erreur

**Comment by AxenoDev** [comment]
oui ?

**Comment by fuzeblocks** [comment]
Il la tester du coup

**Comment by AxenoDev** [comment]
bah non sinon il dirait pas ça.

**Comment by fuzeblocks** [comment]
![image](https://github.com/user-attachments/assets/8495908d-7fd2-4531-8211-eb555f572037)

**Comment by fuzeblocks** [comment]
j'ai fortement l'impression que si

**Comment by AxillityWasGay** [comment]
> bah non sinon il dirait pas ça.

j'ai test en local et sur le serv dev

**Comment by AxillityWasGay** [comment]
> Peut être parce que tu utilises l'annotation Named
> ![image](https://github.com/user-attachments/assets/506a2e33-39c9-46fc-b5de-f02b97a7306f)
> 
> 

oh okay, je vais voir chez moi

**Comment by fuzeblocks** [comment]
D'ailleurs attention avec la taille de l'inventaire au dela de 54 joueur cela va crée une erreur 
![image](https://github.com/user-attachments/assets/99046d65-0c7e-4993-9fb2-e31f8b3112a2)

**Comment by AxillityWasGay** [comment]
> D'ailleurs attention avec la taille de l'inventaire au dela de 54 joueur cela va crée une erreur 
> ![image](https://github.com/user-attachments/assets/99046d65-0c7e-4993-9fb2-e31f8b3112a2)
> 

okay, je vais faire des pages au pire

**Comment by AxenoDev** [comment]
Utilise l'api de Xernas 💀
